name: CD Pipeline

on:
  workflow_run:
    workflows : ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run : sudo docker pull jbscharan123/cicd-pipeline:latest
    - name: Delete Old docker Container
      run : sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run : sudo docker run -d 8501:8501 --name cicd-pipeline-container jbscharan123/cicd-pipeline
